version: '3.8'
services:
  
  chatbot:
    build:
      context: .
      dockerfile: ./chatbot_app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - shared_volume:/app/shared_dir
    depends_on:
      - api_chemtsv2
    networks:
      - chatmolgen_network
  
  api_chemtsv2:
    build:
      context: .
      dockerfile: ./api_chemtsv2/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - shared_volume:/app/shared_dir
    networks:
      - chatmolgen_network

  interface:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - shared_volume:/app/shared_dir
    networks:
      - chatmolgen_network
  
  model_builder:
    build:
      context: .
      dockerfile: ./model_builder_app/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - shared_volume:/app/shared_dir
    networks:
      - chatmolgen_network

volumes:
  shared_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/shared_dir
      o: bind

networks:
  chatmolgen_network:
    driver: bridge