services:
  chatbot:
    build:
      context: .
      dockerfile: ./chatbot_app/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - CHATBOT_PORT=${CHATBOT_PORT}
    ports:
      - "${CHATBOT_PORT}:${CHATBOT_PORT}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_BUILDER_PORT=${MODEL_BUILDER_PORT}
      - ANALYSIS_PORT=${ANALYSIS_PORT}
      - CHEMTS_PORT=${CHEMTS_PORT}
    volumes:
      - shared_volume:/app/shared_dir
    user: "${USER_ID}:${GROUP_ID}"
    depends_on:
      - api_chemtsv2
    networks:
      - chatchemts_network

  model_builder:
    build:
      context: .
      dockerfile: ./model_builder_app/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - MODEL_BUILDER_PORT=${MODEL_BUILDER_PORT}
    ports:
      - "${MODEL_BUILDER_PORT}:${MODEL_BUILDER_PORT}"
    environment:
      - MODEL_BUILDER_PORT=${MODEL_BUILDER_PORT}
    volumes:
      - shared_volume:/app/shared_dir
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - chatchemts_network
 
  analysis:
    build: 
      context: .
      dockerfile: ./analysis_app/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - ANALYSIS_PORT=${ANALYSIS_PORT}
    ports:
      - "${ANALYSIS_PORT}:${ANALYSIS_PORT}"
    environment:
      - ANALYSIS_PORT=${ANALYSIS_PORT}
    volumes:
      - shared_volume:/app/shared_dir
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - chatchemts_network
  
  api_chemtsv2:
    build:
      context: .
      dockerfile: ./api_chemtsv2/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - CHEMTS_PORT=${CHEMTS_PORT}
    ports:
      - "${CHEMTS_PORT}:${CHEMTS_PORT}"
    environment:
      - CHEMTS_PORT=${CHEMTS_PORT}
    volumes:
      - shared_volume:/app/shared_dir
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - chatchemts_network

volumes:
  shared_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/shared_dir
      o: bind

networks:
  chatchemts_network:
    driver: bridge
